security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    role_hierarchy:
        ROLE_EMPLOYEE: ROLE_USER
        ROLE_MODERATOR: ROLE_EMPLOYEE
        ROLE_OPERATOR: ROLE_EMPLOYEE
        ROLE_STOREKEEPER: ROLE_EMPLOYEE
        ROLE_USER_MANAGER: ROLE_EMPLOYEE
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_OPERATOR, ROLE_STOREKEEPER, ROLE_USER_MANAGER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        # User in memory
        users_in_memory:
            memory:
                users :
                    user:
                        password: user
                        roles: ROLE_USER
                    moderator:
                        password: moderator
                        roles: ROLE_MODERATOR
                    operator:
                        password: operator
                        roles: ROLE_OPERATOR
                    storekeeper:
                        password: storekeeper
                        roles: ROLE_STOREKEEPER

                    user_manager:
                        password: user_manager
                        roles: ROLE_USER_MANAGER
                    admin:
                        password: admin
                        roles: ROLE_ADMIN

                    super_admin:
                        password: super_admin
                        roles: ROLE_SUPER_ADMIN

        # User in database
        users_in_database:
            entity:
                class: App\Entity\User
                property: userName

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: lazy

            anonymous: true
            provider: users_in_database

            #http_basic: true



            form_login:
                login_path: login
                check_path: login
                default_target_path: home

            logout:
                path: logout
                target: game_index

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/profile, roles: ROLE_USER }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        # With encoder: BCrypt , Argon2i , PBKDF2...
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
